### ISSUE TITLE
youtube video are not loaded automatically

### ISSUE THREAD

**Issue by dsauvage** [jean-emmanuel/spip-fat#4]
On latest Firefox, Chromium, Chrome version, youtube video are not loaded automatically using the `<youtube|id=ID_VIDEO>` tag, A click on a generic play icon is needed.

![fat-youtube-tag](https://cloud.githubusercontent.com/assets/1416228/9651455/0e28911e-5222-11e5-8000-cf41e6fbda9a.png)

For a better end-user experience, could we get the same behaviour of dailymotion and vimeo for the youtube tag? that is the first picture of the video is showned, 
and then we can click for the video to be played ....

**Comment by jean-emmanuel** [comment]
Youtupe public api (v2) was dropped recently, adding support for v3 will fix this issue (coming with next update) but will require users to set their own youtube api key in the config file `mes_fonctions.php`.

**Comment by dsauvage** [comment]
On 09/03/2015 11:00 AM, jean-emmanuel wrote:
>
> Youtupe public api (v2) was dropped recently, adding support for v3 
> will fix this issue (coming with next update) but will require users 
> to set their own youtube api key in the config file |mes_fonctions.php|.
>
Excellent,

thanks for your prompt feedback

**Comment by jean-emmanuel** [comment]
Fixed ! Relevant commit is a7a25477c5fd41cc111e3d211bed16b2a14422bb, the others are just mistypings fixed and me messing with git...

**Comment by dsauvage** [comment]
On 09/03/2015 11:02 AM, David SAUVAGE - AdaLabs Ltd wrote:
> On 09/03/2015 11:00 AM, jean-emmanuel wrote:
>>
>> Youtupe public api (v2) was dropped recently, adding support for v3 
>> will fix this issue (coming with next update) but will require users 
>> to set their own youtube api key in the config file |mes_fonctions.php|.
>>
> Excellent,
>
> thanks for your prompt feedback

Great thanks for the udpate

Although I updated mes_fonctions.php to add my api key, it did not work 
directly for me.
A simple work-around to get it working was to modify the following in 
modeles/youtube.html
- SET{apikey,#YT_API_KEY}
+ SET{apikey,<my-real-key>}

I guess  #YT_API_KEY is not define in my case ....

FYI, all the project files contain the executable flag, that is not 
recommended. The following can remove the exec. flag for all files:
$ find . -type f -exec chmod a-x {} \;



Cheers

--
David

**Comment by jean-emmanuel** [comment]
So that explained why my commit was all messed up... thank you. Now, did you empty your cache after updating mes_fonctions.php ? It should do the trick.

**Comment by dsauvage** [comment]
On 09/03/2015 02:22 PM, jean-emmanuel wrote:
>
> So that explained why my commit was all messed up... thank you. Now, 
> did you empty your cache after updating mes_fonctions.php ? It should 
> do the trick.
>
Yes I cleanned the cash after updating any files ....
I just tried again, it does not work wish an empty cache.

How SPIP knows about #YT_API_KEY ? we may need to register it ...

**Comment by jean-emmanuel** [comment]
I added some code in mes_fonctions.php you might not have seen (line 42): 
```
	function balise_YT_API_KEY($p) {
	    $p->code = $GLOBALS['youtube_api_key'];
	    return $p;
	}
	function youtubeID($url) {
	    if (strpos($url,'youtube.com') !== false) {
	        return end(explode('?v=',$url));
	    } else if (strpos($url,'youtu.be') !== false) {
	        return end(explode('.be/',$url));
	    }
	}
	function vimeoID($url) {
	    if (strpos($url,'vimeo.com') !== false) {
	        return end(explode('.com/',$url));
	    }
	}
	function dailymotionID($url) {
	    if (strpos($url,'dailymotion.com') !== false) {
	        return reset(explode('_',end(explode('/video/',$url))));
	    }
	}
```
The first function defines `#YT_API_KEY` (`$GLOBALS['youtube_api_key']` must be defined), the others allow videos to be included using their url directly (see docs).

**Comment by dsauvage** [comment]
On 09/03/2015 02:37 PM, jean-emmanuel wrote:
>
> I added some code in mes_fonctions.php you might not have seen (line 42):
>
>
the following solve the issue

|function balise_YT_API_KEY($p) { - $p->code = $GLOBALS['youtube_api_key']; |||+ $p->code = "\$GLOBALS['youtube_api_key']";|  return $p; |

**Comment by jean-emmanuel** [comment]
Somehow, both version worked for me, but since yours seems more core-compliant, here we go https://github.com/jean-emmanuel/spip-fat/commit/e6485ca619531aaf8ae6b1d236dd59b34d0b20a3

**Comment by dsauvage** [comment]
On 09/03/2015 03:00 PM, jean-emmanuel wrote:
>
> Somehow, both version worked for me, but since yours seems more 
> core-compliant, here we go e6485ca 
> <https://github.com/jean-emmanuel/spip-fat/commit/e6485ca619531aaf8ae6b1d236dd59b34d0b20a3>
>
>
FYI, I am running SPIP 3.0.20 [22255]
